# www/theme.css is generated by tools/build-theme.R (the app's theme as
# overrides of the stock bslib theme). These tests check the parts of that
# script that are plain functions, and that the committed file is current.

source(file.path(app_root, "tools", "build-theme.R"), local = TRUE)

test_that("css_split cuts rules and declarations at the top level only", {
  css <- '@charset "UTF-8";a{color:red}@media (min-width:1px){b{c:d}e{f:g}}h::after{content:"}"}'
  expect_equal(css_split(css),
               c('@charset "UTF-8";', "a{color:red}", "@media (min-width:1px){b{c:d}e{f:g}}",
                 'h::after{content:"}"}'))
  expect_equal(css_split("color:red;background:url(data:image/png;base64,AA==);x:'a;b'", decls = TRUE),
               c("color:red", "background:url(data:image/png;base64,AA==)", "x:'a;b'"))
  expect_equal(css_split("color:red", decls = TRUE), "color:red")
})

test_that("css_delta keeps only what the custom stylesheet changes or adds", {
  stock  <- "/* c */a{color:blue;margin:0}b{top:0}@media print{a{color:black}}@font-face{font-family:X}"
  custom <- "a{color:teal;margin:0}b{top:0}@media print{a{color:black;border:0}}@font-face{font-family:X}c{left:0}@font-face{font-family:Y}"
  expect_equal(css_delta(custom, stock),
               c("a{color:teal}", "@media print{a{border:0}}", "c{left:0}", "@font-face{font-family:Y}"))
  expect_equal(css_delta(stock, stock), character(0))
})

test_that("css_delta refuses a custom stylesheet that drops something", {
  expect_error(css_delta("a{color:teal}", "a{color:blue}b{top:0}"), "drops 1 rule")
  expect_error(css_delta("a{color:teal}", "a{color:blue;margin:0}"), "drops .margin.")
})

test_that("the app theme sets the teal accent and Inter", {
  css <- paste(readLines(file.path(app_root, "www", "theme.css"), warn = FALSE), collapse = "\n")
  expect_match(css, "--bs-primary: #0D9488", fixed = TRUE)
  expect_match(css, "--bs-body-font-family: Inter", fixed = TRUE)
  expect_match(css, ".selectize-dropdown .active", fixed = TRUE)
})

test_that("www/theme.css is current for the bslib version it was built with", {
  skip_on_ci()   # starts two background Shiny apps
  skip_if_not_installed("callr")
  current <- readLines(file.path(app_root, "www", "theme.css"), warn = FALSE)
  built_with <- sub(".*with bslib ([0-9.]+)\\..*", "\\1", current[1])
  skip_if(built_with != as.character(packageVersion("bslib")),
          paste("www/theme.css was built with bslib", built_with))
  expect_equal(build_theme_css(app_root), current)
})
